### ISSUE TITLE
Autocomplete on Iphone

### ISSUE THREAD

**Issue by raiymbekB** [beholdr/maska#151] opened 2023-05-09 14:42 UTC
### Describe the bug

If you try to use autocomplete after entering some symbols into input field it won't work for the first time. Next click on autocomplete will work. Only on Iphone. Also mask must translate to uppercase.

### Steps to reproduce

https://github.com/beholdr/maska/assets/117362543/94ff92d7-559f-4000-b3fc-a4fed8aba1f3

**Comment by beholdr** [comment] 2023-05-10 08:56
Honestly, I can't reproduce this on my iphone


https://github.com/beholdr/maska/assets/741973/b30ad36c-ee48-470a-ad51-cbc8b654763a

**Comment by beholdr** [comment] 2023-05-10 09:30
Do you use standard iphone keyboard?

**Comment by raiymbekB** [comment] 2023-05-10 09:32
Yes, both of us used standard keyboard

**Comment by beholdr** [comment] 2023-05-10 09:59
Strange, but I can’t reproduce it. Tried on two iPhones with 16.3.1 and 16.4.1, both with standard keyboards. Work as intended. So I close this issue for now, until maybe someone else runs into this issue.

**Closed by beholdr** 2023-05-10 09:59 UTC
